<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Alfaro" failures="2" tests="2" name="Test Test" time="34.498" errors="0" timestamp="2025-03-31T13:26:58 CST">
  <testcase classname="JavaSeleniumTest.temp1.Test4" name="submitOrder" time="8.674">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at JavaSeleniumTest.temp1.Test4.submitOrder(Test4.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="JavaSeleniumTest.temp1.Test4" name="submitOrder" time="8.863">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at JavaSeleniumTest.temp1.Test4.submitOrder(Test4.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="JavaSeleniumTest.temp1.Test4" name="OrderHistory" time="0.0">
    <ignored/>
  </testcase> <!-- OrderHistory -->
</testsuite> <!-- Test Test -->
